### PR TITLE
release: 2.2.0

### PR DESCRIPTION
**Pull request by gszr**

### CODE REVIEW

**Comment by gszr** [comment]
Please hold on this one; we need to bump the OR version.

**Review by hutchic — COMMENTED** [review]
should the `Aliases` symlink be updated?

**Review by kikito — APPROVED** [review]
I think this PR should also remove the `/Formula/openresty@1.15.8.3.rb` file, which isn't used any more (Kong now depends on the 1.17.8.2 one).

Apart from that, I have tested the formulas locally and they seem to work ok, so I am approving conditional on the removal of the file.

**Comment by gszr** [comment]
@kikito 

Good point! My thought process is that given we are still supporting OR 1.15.8.3 in Kong 2.2, I'd leave the formula there for convenience. Any objections? We will remove it once we drop support for OR 1.15.8.3.

Thanks for the review.

**Comment by dndx** [comment]
@kikito @gszr It should be fine to keep the old version of OpenResty around for a bit longer and remove it in the 2.3 release. We did this before for older versions too.

**Review by dndx — APPROVED** [review]

**Comment by kikito** [comment]
> It should be fine to keep the old version of OpenResty around for a bit longer and remove it in the 2.3 release.

Ok, agreed! This PR is approved as-is.

**Pull request merged**
