### PR TITLE
fix(kong): Various Post 3.0 Release Fixes

### PR DESCRIPTION
**Pull request by curiositycasualty**
Just some things that didn't make it onto the `release/3.0.0` branch.

### CODE REVIEW

**Review by hanshuebner — APPROVED** [review]

**Review by gszr — APPROVED** [review]
LGTM. 
I don't see a reason why it wouldn't work, but would be nice to test against an m1 env (I can do so on Tue).

**Comment by curiositycasualty** [comment]
On arm:
```
brew test kong
==> Testing kong/kong/kong
==> /opt/homebrew/Cellar/kong/3.0.0/bin/resty -e setmetatable(_G,nil);require("kong.plugins.opentelemetry.proto")
Last 15 lines from /Users/ec2-user/Library/Logs/Homebrew/kong/test.01.resty:
	no file './kong/plugins/opentelemetry/proto.so'
	no file '/usr/local/lib/lua/5.1/kong/plugins/opentelemetry/proto.so'
	no file '/opt/homebrew/Cellar/openresty@1.21.4.1/1.21.4.1/openresty/luajit/lib/lua/5.1/kong/plugins/opentelemetry/proto.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file '/opt/homebrew/Cellar/openresty@1.21.4.1/1.21.4.1/openresty/site/lualib/kong.so'
	no file '/opt/homebrew/Cellar/openresty@1.21.4.1/1.21.4.1/openresty/lualib/kong.so'
	no file './kong.so'
	no file '/usr/local/lib/lua/5.1/kong.so'
	no file '/opt/homebrew/Cellar/openresty@1.21.4.1/1.21.4.1/openresty/luajit/lib/lua/5.1/kong.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	(command line -e):1: in function 'inline_gen'
	init_worker_by_lua:44: in function <init_worker_by_lua:43>
	[C]: in function 'xpcall'
	init_worker_by_lua:52: in function <init_worker_by_lua:50>
Error: kong/kong/kong: failed
An exception occurred within a child process:
  BuildError: Failed executing: /opt/homebrew/Cellar/kong/3.0.0/bin/resty -e setmetatable(_G,nil);require("kong.plugins.opentelemetry.proto")
/opt/homebrew/Library/Homebrew/formula.rb:2493:in `block in system'
/opt/homebrew/Library/Homebrew/formula.rb:2429:in `open'
/opt/homebrew/Library/Homebrew/formula.rb:2429:in `system'
/opt/homebrew/Library/Taps/kong/homebrew-kong/Formula/kong.rb:53:in `block in <class:Kong>'
/opt/homebrew/Library/Homebrew/formula.rb:2269:in `block (3 levels) in run_test'
/opt/homebrew/Library/Homebrew/utils.rb:605:in `with_env'
/opt/homebrew/Library/Homebrew/formula.rb:2268:in `block (2 levels) in run_test'
/opt/homebrew/Library/Homebrew/formula.rb:967:in `with_logging'
/opt/homebrew/Library/Homebrew/formula.rb:2267:in `block in run_test'
/opt/homebrew/Library/Homebrew/mktemp.rb:77:in `block in run'
/opt/homebrew/Library/Homebrew/mktemp.rb:77:in `chdir'
/opt/homebrew/Library/Homebrew/mktemp.rb:77:in `run'
/opt/homebrew/Library/Homebrew/formula.rb:2544:in `mktemp'
/opt/homebrew/Library/Homebrew/formula.rb:2261:in `run_test'
/opt/homebrew/Library/Homebrew/test.rb:45:in `block in <main>'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/opt/homebrew/Library/Homebrew/vendor/portable-ruby/2.6.8_1/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/opt/homebrew/Library/Homebrew/test.rb:50:in `<main>'
```

**Comment by curiositycasualty** [comment]
Which is extra funky, because Mac OS doesn't use shared object (`.so`), it should be hunting for a dynamic library (`.dylib`). 🤔

**Comment by curiositycasualty** [comment]
Installing from produced the same error.

**Comment by curiositycasualty** [comment]
With my latest commits, `resty` is able to load the OT plugin as a test of the .proto files' existence and readability.
I negatively tested this by removing `trace_service.proto` locally to cause the test to fail.

Meaning this PR should be ready to review/merge.

**Comment by gszr** [comment]
This should now be ready to review / merge

**Pull request merged**
