### PR TITLE
Use Github Actions

### PR DESCRIPTION
**Pull request by curiositycasualty**
This mainly does 2 things:
  - swaps to Github Actions for CI (instead of travis) and
  - gussies up the existing formulae to meet `brew style` and `brew audit` standards

If `brew style` and `brew audit` are good enough for homebrew-core, they're good enough for your tap.

### CODE REVIEW

**Comment by curiositycasualty** [comment]
You can find an example run here: https://github.com/curiositycasualty/homebrew-kong/runs/4514219803

**Comment by gszr** [comment]
Great stuff!

Any ideas why the run isn't showing up under the checks?

**Comment by curiositycasualty** [comment]
Nope! Let me look into it.
My guess would be that it's disabled in the repo's settings, but I'll need to wrangle github admin to disapprove that theory.

**Comment by curiositycasualty** [comment]
closing in favor of https://github.com/Kong/homebrew-kong/pull/189

**Pull request closed without merging**
